### ISSUE TITLE
updated version 2.5.x?

### ISSUE THREAD

**Issue by papayaah** [happilymarrieddad/vue-socketcluster#1]
hi @happilymarrieddad do you by chance have an updated version? Vue is now 2.5.13, the way you set the instance methods here doesn't work anymore. I'm fairly new to Vue so i wouldn't know yet how to update yours.

**Comment by papayaah** [comment]
incase someone tried to use your stuff, i was able to modify mine so it looks like this now:

```
                    let sockets = this.$options['sockets']
                    if(!sockets) return

                    methods.forEach(function (event) {
                        socket.on(event, function (data,respond) {
                            if (sockets.hasOwnProperty(event)) {
                                self.$options.sockets[event].call(self, data, respond);
                            }
                        })
                    })
```

in the ` Vue.mixin({ ... })`

**Comment by happilymarrieddad** [comment]
@mickeyren Hey man, I am in fact working on a 2.5 version as we speak. It's part of a much larger solution. I started this project quite a while back and stopped using almost right after. I'll post here when I finish the "new" one. I'll build it with rollup and what not so it's easy to integrate into almost any project.

**Comment by papayaah** [comment]
wow that's great! In the meantime in case someone wants to use your stuff, they can change the line where it tries to discover if `sockets` property has been declared in the component with this:

```
                    let sockets = this.$options['sockets']
                    if(!sockets) return

                    // for custom events, not in the methods array
                    for (var key in sockets) {
                        if (self.$options.sockets.hasOwnProperty(key) && methods.indexOf(key) < 0) {
                            socket.on(key,function(data, respond) {
                                self.$options.sockets[key].call(self, data,respond);
                            })
                        }
                    }

                    methods.forEach(function (event) {
                        socket.on(event, function (data,respond) {
                            if (sockets.hasOwnProperty(event)) {
                                self.$options.sockets[event].call(self, data, respond);
                            }
                        })
                    })
```

I haven't gotten into the `subscriptions` part yet but when i fix that i'll post the code here too.

**Comment by maarteNNNN** [comment]
@happilymarrieddad any updates on this?

**Comment by happilymarrieddad** [comment]
@maarteNNNN @mickeyren hey guys, I should have the new version up tonight.

**Comment by happilymarrieddad** [comment]
https://www.npmjs.com/package/vue2-socketcluster
