### ISSUE TITLE
bug with events in socket scope

### ISSUE THREAD

**Issue by fkhateeb** [happilymarrieddad/vue-socketcluster#2]
Hi @happilymarrieddad 
- [key] which points for non socket methods and not in subscriptions  has been changed with the last subscription method .
- Emitting events callback not correct it's two parameters not three.
change lines 59 to 64 with this code 
` for (var ikey in self.$options.sockets) {
                            if (self.$options.sockets.hasOwnProperty(ikey) && methods.indexOf(ikey) < 0) {
                                socket.on(ikey, function (data, respond) {
                                    self.$options.sockets[ikey].call(self, data, respond);
                                })
                            }
                        }`

thank you for this plugin.

**Comment by happilymarrieddad** [comment]
Oh hey I didn't know anyone use this plugin =). Cool!! Well, I made it and kind of abandoned it because I went a different direction but I'll do my best to help you.

**Comment by fkhateeb** [comment]
ok just update it with code i sent you and everything fixed 👍

**Comment by fkhateeb** [comment]
also thank you for creating helping libs and tutorials

**Comment by happilymarrieddad** [comment]
Yea, you can make a pull request if you want and I'll for sure push it up.

**Comment by happilymarrieddad** [comment]
@fkhateeb hey man here is the new library.
https://www.npmjs.com/package/vue2-socketcluster
